### ISSUE TITLE
Activity information not course specific

### ISSUE THREAD

**Issue by shashwatkathuria** [WikiEducationFoundation/WikiEduDashboard#3847] opened 2020-03-05 20:41 UTC
### What is happening?
The 'Activity' Tab for a specific course gives information about user's whole activity rather than only course specific activity.

### To Reproduce

   1. Make 2 new basic programs as an instructor. Make a student join both of them.
   2. Assign the student one article in each course.
   3. Make edits to both articles and also do manual update (/manual_update) for pulling the revisions.
   4. See 'Activity' tab for each course. 
   5. See error

### Expected behavior
Only the content related to the specific course should be shown in the 'Activity' Tab, because the Activity Tab is of the specific course.

### Screenshots
![Screenshot from 2020-03-06 02-04-08](https://user-images.githubusercontent.com/37243661/76023681-9bd98380-5f4f-11ea-97bd-cdcacc72297e.png)
![Screenshot from 2020-03-06 02-04-16](https://user-images.githubusercontent.com/37243661/76023694-a136ce00-5f4f-11ea-845c-cab25ca6488b.png)
![Screenshot from 2020-03-06 02-04-21](https://user-images.githubusercontent.com/37243661/76023696-a4ca5500-5f4f-11ea-89da-5dbade106c9e.png)
![Screenshot from 2020-03-06 02-04-26](https://user-images.githubusercontent.com/37243661/76023703-a85ddc00-5f4f-11ea-9252-799851e5fc78.png)

### System Information

 - OS: Linux Ubuntu 18.04
 - Browser Chrome
 - Latest Version

**Comment by ragesoss** [comment] 2020-03-05 20:44
This is the intended behavior, but it could be useful to add a filter so that you have the option of viewing only course-specific revisions.

**Comment by shashwatkathuria** [comment] 2020-03-05 21:01
@ragesoss Should I go forward with implementing that feature? I think that could be useful.

**Comment by shashwatkathuria** [comment] 2020-03-11 20:44
@ragesoss 
I am currently working on this and need some clarification on how to filter out the course specific revisions in the json builder of course revisions. So what I'm trying to do is querying out all the assignments of the course and plucking their sandbox urls, then I query for revisions which have their article url the same as the sandbox urls obtained earlier. Is this okay or there is another approach for getting the course specific revisions (as I think this is not a straightforward approach)?

**Comment by ragesoss** [comment] 2020-03-16 14:49
Probably the way to do this will be with client-side filtering: take the revisions received from the server, and filter out any that don't match up to one of the articles received from the server. Probably the cleanest way to do this would be to add `article_id` to the revision attributes, so that the id could be used as the basis for filtering.

**Comment by shashwatkathuria** [comment] 2020-03-16 21:46
@ragesoss 
The problem is that for some articles I have article_id: nil which is why I had to do it an unclean fashion.
![Screenshot from 2020-03-17 03-09-52](https://user-images.githubusercontent.com/37243661/76802120-ffd83380-67fc-11ea-9a33-383453226eac.png)

And neither am I getting any articles.json with the help of which I can filter the information at the client side.
![Screenshot from 2020-03-17 03-13-41](https://user-images.githubusercontent.com/37243661/76802343-7ecd6c00-67fd-11ea-86ab-35f8ccc071c3.png)

**Comment by ragesoss** [comment] 2020-03-16 22:09
Whether an article needs to be assigned in order for activity to be counted depends on the `Course` type. For an ArticleScopedProgram, the only activity that counts will be edits to assigned articles or to articles that are in one of the `Category` records for the course. However, for any activity that is in that scope, there will be an `ArticlesCourses` record for the article and the course, and the article will be part of the list of articles shown on the Articles tab (and sent via the `articles.json` endpoint).

For the default course type, articles don't need to be assigned for activity to be counted; the Dashboard is supposed to track any articles edits on the tracked wiki(s) for the course that happen during the course timeframe.

In either case, client-side filtering based on the data for the `articles` reducer should work. (Filtering will also need to be done based on timestamp, to filter out activity that is for one of the in-scope articles but before/after the course timeframe.)

**Comment by ragesoss** [comment] 2020-07-07 20:13
I've just merged the PR for this, #4002 

This version is better than nothing, but I think it needs some significant re-architecture before it will really be useful. Here's an example course where the people running it have asked for this exact feature: https://outreachdashboard.wmflabs.org/courses/Museu_Paulista/Wikiconcurso_do_Museu_Paulista_2020/activity

This is an Article Scoped Program, and most of the edits made by the participants are not to any of the tracked articles.

Switching to 'course specific' mode shows nothing at all, even if you click 'See More' many times. This is because the strategy of fetching more and more revisions from the full set of user revisions won't predictably find any course-specific revisions, if there are hundreds or thousands of more recent out-of-scope revisions.

I think the way this needs to work is with a separate query which just returns the course scoped revisions. Maybe this can happen via an optional param on the revisions.json query, so that the controller will find the tracked revisions and send the details for only those.

**Closed** 2020-07-16 15:29 UTC
Labels: bug
