### ISSUE TITLE
In Firefox on Linux, cannot position the cursor in block edit window by clicking

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#548] opened 2015-12-18 00:13 UTC
I've only done this on Debian, but we ran into very similar issues in the old edit interface that affected Firefox on all systems.

**Comment by bmathews** [comment] 2015-12-18 00:40
Can't reproduce on FF on OSX

**Comment by ragesoss** [comment] 2015-12-18 00:42
To be clear, I can position the cursor at the beginning or end of the text, just not in the middle at an arbitrary postion. Also The up and down arrow keys don't work to change lines (although left and right work for iterating over characters).

**Comment by bmathews** [comment] 2015-12-18 00:42
@ragesoss Do you have any of those issues here? http://trix-editor.org/

**Comment by ragesoss** [comment] 2015-12-18 00:43
@bmathews No.

**Comment by bmathews** [comment] 2015-12-18 00:47
Thanks! I'm getting a Debian vm to try to reproduce.

**Comment by ragesoss** [comment] 2015-12-18 18:36
I've replicated the problem on Debian, Ubuntu, as well as on Android Firefox. But it seems to be Linux-only.

**Comment by bmathews** [comment] 2015-12-18 18:42
I was able to reproduce on the Debian VM. Trying to track down the issue now. Thanks!

**Comment by bmathews** [comment] 2015-12-18 19:11
Fixed via ce713d5cb9276618226692a68a9a1a2d74401345

:rage:

**Comment by ragesoss** [comment] 2015-12-18 19:50
I can now click, but it doesn't actually let me type in the cursor position on Iceweasel.

**Closed** 2015-12-23 22:25 UTC
Labels: bug

**Comment by bmathews** [comment] 2015-12-23 22:27
@ragesoss Fixed now. The wysiwyg was wrapped in a `<label>` element. When you click the wysiwyg, the event would bubble to the label, then the label would transfer focus from the `contenteditable` element to the first `form` element in the label, which was the bold button.
