### ISSUE TITLE
Clone a course

### ISSUE THREAD

**Issue by thenickcox** [WikiEducationFoundation/WikiEduDashboard#384] opened 2015-09-16 17:09 UTC
As a professor that has currently taught a course, I should be able to clone that course (and its associated weeks and blocks) through the course creator.

**Comment by ragesoss** [comment] 2015-09-22 16:15
@thenickcox git A couple more things before we can close this:

* The 'school' field should be present. Sometimes an instructor may have changed universities, but still wants to run a similar course.
* The form should validate setting meeting days and blackout days.
* The dates are not being set to today's date. They start out blank, but then the original course dates appear in those fields after you interact with another field (such as term). (The validation to make sure you modify them works nicely, but in cases where an instructor is cloning a course for a second concurrent section, they may actually want to put in the same dates.) Explicitly setting them to Today.date in the clone manager should reduce the potential for confusion.

**Comment by thenickcox** [comment] 2015-09-22 17:26
Great news! These were all easy to implement. (I'm gaining some velocity with React!) See my latest commit.

**Comment by ragesoss** [comment] 2015-09-22 18:12
@thenickcox Whoops, one more thing I didn't notice until I started writing a test for the manager: timeline dates. We're currently cloning those. We need, instead, to set those also to Today.date and have the user update them.

**Comment by ragesoss** [comment] 2015-09-22 18:47
I reset the timeline dates in the clone manager, but haven't started the frontend part.

**Comment by thenickcox** [comment] 2015-09-22 19:31
I'm not completely convinced that the manager needs a unit test; its functionality is exercised in the feature spec.

**Comment by ragesoss** [comment] 2015-09-22 19:38
The feature test didn't catch that the original timeline dates were being cloned. The unit tests document the intended behavior more explicitly, and there may be other edge cases in the future that we need to account for and test against. (Writing the test was also useful for me in thinking through and verifying all the things that we want to happen with cloning.)

**Comment by thenickcox** [comment] 2015-09-22 19:46
Then that's a great reason for a test!

**Comment by ragesoss** [comment] 2015-09-22 20:14
I was ambiguous up above, but I'm leaving the bit about adding timeline dates into the clone modal to you, @thenickcox

**Comment by thenickcox** [comment] 2015-09-22 20:37
Thanks for the clarity!!

**Closed** 2015-09-22 20:52 UTC
Labels: enhancement
