### ISSUE TITLE
Check marks in wizard options do not appear in Firefox

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#121] opened 2015-06-15 17:53 UTC

**Comment by ntdb** [comment] 2015-06-22 21:22
I assume you mean the check marks as seen in the attached image? Can't reproduce in FF 36.0.4 on Mac, can you re-check this?
![screen shot 2015-06-22 at 2 21 34 pm](https://cloud.githubusercontent.com/assets/2095463/8293417/17f3450c-18ea-11e5-98b3-9082d3f11009.png)

**Comment by ragesoss** [comment] 2015-06-22 21:43
Iceweasel 38.0.1 on Debian Squeeze. I get the same issue on Firefox 37.0.1 on Windows 8.1.

![screenshot from 2015-06-22 14-25-55](https://cloud.githubusercontent.com/assets/848483/8293799/c55f15a2-18ec-11e5-8ec5-01c28b1ede93.png)

**Comment by ntdb** [comment] 2015-06-23 00:41
This seems to be resolved in the latest build (which I'm pushing as soon as Travis gives me the go-ahead).

**Comment by ntdb** [comment] 2015-06-23 01:00
Nope, no luck. The SVG is now gone from Chrome as well. Will get after it in the AM.

**Closed** 2015-06-23 16:37 UTC
Labels: minor bug
