### ISSUE TITLE
Survey navigation with arrows or swipes sometimes causes unexpected behavior

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#810] opened 2016-04-20 20:59 UTC
@hudakdidit During a user test, accidental track pad touches caused the survey to skip around a lot, and sometimes can end you up on a blank screen (from scrolling down accidentally?)

Slider selections (unlike other response) are sometimes zeroed out, when you do this kind of trackpad skipping around.

Disabling trackpad input would be ideal.

**Comment by hudakdidit** [comment] 2016-04-20 21:16
@ragesoss not quite sure I follow. This is reported using a laptop trackpad? What kind of device (if its device-specific).

**Comment by ragesoss** [comment] 2016-04-20 21:17
This was on a Macbook, I believe. Using the trackpad when no input is in focus can result in unexpected behavior, including navigating forward or backward.

**Comment by hudakdidit** [comment] 2016-04-20 21:27
@ragesoss not able to reproduce this behavior, so i'll need steps to reproduce.

Trackpad behaviors can be effective by user-defined system settings. One default on OSX is the swipe left/right in browsers which triggers the forward or back browser history buttons.

I don't believe there isn't a way to disable trackpad input, its native behavior.

**Comment by ragesoss** [comment] 2016-04-20 21:31
@hudakdidit thanks. I'm guessing that it was the OSX swipe navigation, combined with accidentally scrolling down to the blank region.

**Comment by hudakdidit** [comment] 2016-04-20 21:33
Oh ok gotcha. I just pushed a commit that prevents the extra space below certain slides, the container will now adapt to the height of each slide. Ok to close?

**Comment by hudakdidit** [comment] 2016-04-20 21:34
Once staging deploys maybe we can test out again to confirm.

**Comment by ragesoss** [comment] 2016-04-20 21:36
I'll keep an eye on it. I think there are some other glitches related to key board navigation and other forms of navigation besides click the buttons, which depend on what is in focus. I'll try to pin something down better.

**Comment by ragesoss** [comment] 2016-04-20 21:53
@hudakdidit it looks like this causes a regression in the question cut-off issue.

![bleh](https://cloud.githubusercontent.com/assets/848483/14691712/9e5a633a-0707-11e6-957a-ce9ceeaafd9e.png)
![screen shot 2016-04-20 at 2 51 39 pm](https://cloud.githubusercontent.com/assets/848483/14691717/a76cff28-0707-11e6-939d-b46ca6eb2071.png)

**Comment by hudakdidit** [comment] 2016-04-20 21:57
Not technically a regression, but causes a similar bug. Working on a fix.

**Comment by hudakdidit** [comment] 2016-04-20 22:44
@ragesoss just pushed a fix for this cut-off bug. I'll confirm once it deploys

**Comment by hudakdidit** [comment] 2016-04-20 23:31
I think I go it. Re-open if still seeing this issue.

**Closed by hudakdidit** 2016-04-20 23:31 UTC
Labels: minor bug, surveys
