### ISSUE TITLE
Instructor survey stops working in the middle

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#759] opened 2016-04-08 18:35 UTC
@hudakdidit I'm guessing that one of the conditional questions is what is breaking it. Nothing shows up after the question about 'which resources did you use': https://dashboard-testing.wikiedu.org/surveys/5?preview

**Comment by hudakdidit** [comment] 2016-04-08 20:37
@ragesoss thanks for the report. The new one-at-a-time ux has caused some of the conditional behavior to regress. Working on it..

**Comment by hudakdidit** [comment] 2016-04-12 16:21
@ragesoss should be fixed now. You were right about it being caused by conditional questions. The front-end logic for comparing answer values to conditional questions should be more robust at handling html now.

**Closed by hudakdidit** 2016-04-12 16:21 UTC
Labels: surveys
