### ISSUE TITLE
In the Students details view, ArticleViewer only shows edits by assigned group members

### ISSUE THREAD

**Issue by ragesoss** [WikiEducationFoundation/WikiEduDashboard#4023] opened 2020-05-08 21:54 UTC
#3143 # What is happening?
ArticleViewer with authorship highlighting is available from both the Students tab details view, and from the Articles tab.

On the Articles tab, it will show authorship data for any student in the course who has edited that article. For example: https://dashboard.wikiedu.org/courses/Georgetown_University/Culture_Medicine_and_Gender_(Spring_2020)/articles/edited?showArticle=175357

On the Student tab details view, it only shows the authorship for the set of students who are assigned to that articles. For example, here's it's missing Jane4dc:
https://dashboard.wikiedu.org/courses/Georgetown_University/Culture_Medicine_and_Gender_(Spring_2020)/students/articles/Hadleyggeorgetown?showArticle=175357

### Expected behavior
ArticleViewer should show all the students who edited a given article, even when viewed from the Students tab assignment list.

**Comment by h-ranjan1110** [comment] 2020-06-12 09:17
@ragesoss the links that you gave are taking much time to open. like it loads for 2-3 minutes and then stops. my internet connection is good, other sites work properly. can you please see what is this issue.

**Comment by rahahahat** [comment] 2020-09-29 16:19
Has this issue been resolved, because i can see jane4dc in the Students tab details view.

**Comment by ragesoss** [comment] 2020-09-29 16:33
In this example, I'm not sure. jane4dc was added as a group member, so we can't tell from that link whether this is still a bug. @BaileyMcKelway has been working on improvements to ArticleViewer, but I'm not sure whether they changed this behavior.

You should be able to set up the same situation locally by adding those same users to an example course (with the start/end dates from that course), doing a course stats update to pull in their edits, and assigning all the student except jane4dc to that article.

**Comment by rahahahat** [comment] 2020-09-29 16:40
Alright thanks, i'll try to reproduce the bug. However, would i need to set-up OAuth for this functionality?

**Comment by ragesoss** [comment] 2020-09-29 17:01
No, the default OAuth credentials allow you to sign into the dev instance using any Wikipedia account, which is all you'll need.

Setting up your own OAuth credentials is only required to test OAuth edit actions.

**Comment by rahahahat** [comment] 2020-10-02 01:12
Hello @ragesoss, 
I have somewhat replicated the course structure, added 4 students (editors) : `Jane4dc` `Amm567` `Ashiannaj` `Hadleyggeorgetown` and pulled their edits. Afterwards, I added the `Postpartum depression` article and assigned it to all except `Jane4dc`.
 This is the behaviour I got from the article viewer: 
1) Upon reviewing the Article via the Articles tab with a URL like:
   `http://localhost:3000/courses/test/test/articles/edited?showArticle=18`
    I can see all Editors who have edited the article.
![Screenshot from 2020-10-02 02-01-50](https://user-images.githubusercontent.com/62028695/94877816-854aca80-0453-11eb-849e-53f827b8811f.png)
2) Upon reviewing the Article via the Students (Editors) tab with a URL like:
    `http://localhost:3000/courses/test/test/students/articles/Amm567?showArticle=18`
     I can see all Editors except `Jane4dc`.
![Screenshot from 2020-10-02 02-07-17](https://user-images.githubusercontent.com/62028695/94878069-3ea9a000-0454-11eb-9c99-0d57562878ed.png)

#### Is this what the bug is supposed to look like? Also could you please point me towards a starting point so that I can work on it.
 Thanks.

**Comment by rahahahat** [comment] 2020-10-08 01:56
@ragesoss can i work on this issue?

**Comment by ragesoss** [comment] 2020-10-08 02:10
Yes, go for it. Please leave a comment if you're no longer actively working
on it.

**Comment by ragesoss** [comment] 2020-10-08 15:54
And yes, that's what the bug is supposed to look like. Sorry, this slipped through I forgot to respond before.

As for where to start... look for the places in the codebase where `ArticleViewer` is used, and the data flow for how the list of users that populate the legend differs between them. ie, the list of group members gets passed to the component when it's in the SelectedStudent view as in the bug, while the list of contributors is determined differently for ArticleViewer when viewed from the Articles tab.

**Comment by rahahahat** [comment] 2020-10-08 19:10
> And yes, that's what the bug is supposed to look like. Sorry, this slipped through I forgot to respond before.
> 
> As for where to start... look for the places in the codebase where `ArticleViewer` is used, and the data flow for how the list of users that populate the legend differs between them. ie, the list of group members gets passed to the component when it's in the SelectedStudent view as in the bug, while the list of contributors is determined differently for ArticleViewer when viewed from the Articles tab.

Thanks a lot for the information, I'll get started on it then.

**Comment by rahahahat** [comment] 2020-10-11 02:54
Hello @ragesoss, I have been working on the bug, and found the source of the Bug. When the `ArticleViewer.jsx` component is rendered from the `Students` tab, The users that are passed on to it are 'extracted' from the assignments of a particular course. The data flow is as:
`Course.jsx` -> `StudentsTabHandler.jsx` -> `Articles.jsx` -> `SelectedStudent.jsx` -> `AssignmentList.jsx` -> `Assignment.jsx` -> `ArticleViewer.jsx`. 
The assignments are fetched in `Articles.jsx` container via a dispatch passed from `StudentsTabHandler.jsx` and then passed down all the component hierarcy resulting in the bug. On the other hand when an `ArticleViewer.jsx` component is invoked from the Articles Tab, in the Data flow hierarcy, the `fetchArticleDetails` function with relevant arguments is called that then updates the `redux-store` with `articleDetails` field, from which the users are passed to `ArticleViewer.jsx`. I have been able to come up with a fix for the bug, however that involves passing in arguments to the `fetchArticleDetails` in the `Assignement.jsx` component. The call is then triggered in the `ComponentDidUpdate` of the `ArticleViewer`, which provides us with the missing user. However, i was wondering whether I was allowed to make the following change or should i look for some other solution?

**Comment by ragesoss** [comment] 2020-10-12 16:55
@rahahahat Cool! That sounds like it might be an appropriate solution. Please open a pull request so I can understand precisely what your solution is.

**Comment by rahahahat** [comment] 2020-10-12 20:18
Hello @ragesoss,
My current solution causes a small bug for users that don't have any assigned articles, in this case `Jane4dc`. I'm just about done figuring out why that is happening, and will open the pull request as soon as I'm done. Thanks for all the help.

**Comment by rahahahat** [comment] 2020-10-13 00:23
@ragesoss, I have submitted the pull request, please review it. Also are there testing files for the `articleViewer.js` which i can explore and test my current changes?

**Comment by rahahahat** [comment] 2020-10-14 03:28
@ragesoss, Hi  have been working on the bug, i have somewhat managed to fix it. First of all since I am directly editing the `articleViewer.jsx` file. This means that all these changes must be compatible at every place where the container is invoked. Altough the bug has been fixed, the current implementation causes some warnings at other places in the code, which can be rectified. But while i was working on it, i found out that an `API` call from the `Assignment.jsx` component seemed to solve problem without creating any warnings. This approach, involves me declaring a `state`, and updating it via `useEffect()`. Please let me know which implementation would be best. I have opened the pull request. Thanks a lot.

**Closed** 2020-10-28 21:39 UTC
Labels: React, bug, newcomer friendly
