### ISSUE TITLE
Missing graphs: analytics assets are not loading on 'Articles Edited' page

### ISSUE THREAD

**Issue by srish** [WikiEducationFoundation/WikiEduDashboard#1794] opened 2018-03-13 03:05 UTC
On the outreach dashboard, in `/Articles Edited,` on clicking 'Changes in structural completeness,' a graph description appears but the visuals are missing. It looks like the analytics assets are not loading on this page. Also, as a user, the term 'Changes in structural...' is hard to understand. 
<img width="1254" alt="screen shot 2018-03-11 at 6 46 46 pm" src="https://user-images.githubusercontent.com/288353/37320372-b10ef596-2630-11e8-88e4-6275ac89993b.png">

**Comment by tuxology** [comment] 2018-03-13 03:56
@srish This could be an issue of missing R packages on the instance where the app is [hosted](https://outreachdashboard.wmflabs.org/courses/SFMOMA/SF_SFMOMA_ArtAndFeminism_2018/articles) as it is related to ORES, but I am not very sure. I'm still trying to wade through the codebase :blush:

**Comment by ragesoss** [comment] 2018-03-13 16:26
It's not missing any packages, as other places that use this same plot code are working, eg: https://outreachdashboard.wmflabs.org/campaigns/artfeminism_2018/ores_plot

The one on the Articles tab of a program used to work as well, but it's not working currently for me either. Here's the stack trace:

NoMethodError

```
undefined method `length' for nil:NilClass

    lib/analytics/histogram_plotter.rb in plot_subtitle at line 96

lib/analytics/histogram_plotter.rb in plot_density at line 155
lib/analytics/histogram_plotter.rb in major_edits_plot at line 38
lib/analytics/histogram_plotter.rb in plot at line 9
app/controllers/ores_plot_controller.rb in course_plot at line 8
Called from: action_controller/metal/basic_implicit_render.rb in send_action
```

**Comment by ragesoss** [comment] 2018-03-13 16:30
@srish if you can come up with a clearer explanation, please do. We want to avoid suggesting that ORES wp10 scores (which are the basis for these plots) are measures of article quality, per se. The idea behind calling it structural completeness is that it is based on the gross structural features of an article rather than the content; it's how much, at the level of headings and wikilinks and ref count, that it 'looks' like a good article to the ORES model.

**Comment by ragesoss** [comment] 2018-03-15 18:33
I've been trying to debug this on the server, but I can't get to the bottom of it. The behavior from the screenshot is a different failure mode from the one I posted the stack trace for above. With the stack trace one, it's (ultimately) a Ruby error, which results in a 500 response and the spinner just keeps spinning forever.

The screenshot is for a 404 error, which probably means an error in the R code (which does not stop execution or log any error details) during graph generation.

I've now seen both failure modes several times each. At least with the 404 error, the course data file does get generated on the server but the graph file does not. However, when I run the same graph generation code from a rails console on the server, it works. And after that, reloading the page will let you see the graph as intended. For example, this will probably only work today: https://outreachdashboard.wmflabs.org/courses/Boston_University/Black_Lunch_Table_@_BU_Arts_Initiative_2/articles

I think to get to the bottom of this, we need to add better logging and validation capabilities to `HistogramPlotter`. Rinruby, which it uses to invoke R from Ruby, by default prints the R output to the console. We can probably change that to capture it to an instance variable, then at the end of the plot routine, check for the existence of the expected file and report an error with the R output if the file doesn't exist.

**Comment by ragesoss** [comment] 2018-09-21 22:06
The 'Articles Edited' page, specifically, is fixed with the new client-side plot, although the other two places that use the R plots are likely still not reliable until #2006 is done.

**Closed by ragesoss** 2018-09-21 22:06 UTC
Labels: Programs & Events Dashboard, bug, help wanted
